continuation_prompt = "[󰅬  ](subtle_text)"
add_newline = true

# Sets user-defined palette
palette = "powerline_colors"

right_format = """$git_state $git_status"""

format = """
 $status\
$cmd_duration
$os\
$username\
[ ](fg:first bg:second)\
$directory\
[ ](fg:second bg:third)\
$git_branch\
[ ](fg:third bg:fourth)\
$character\
[ ](fg:fourth)\
"""

[status]
symbol = " "
success_symbol = "󰄬 "
not_executable_symbol = "󰂭 "
sigint_symbol = "󰹆 "
signal_symbol = "󱐋 " 
not_found_symbol = " "
format = "[$symbol ]($style)"
style = "fg:subtle_text)"
map_symbol = true
disabled = false

[cmd_duration]
min_time = 0
format = "[$duration󱦟 ](fg:subtle_text)"
disabled = false

[shell]
style = "fg:dark_text bg:first"
format = "[ $indicator ]($style)"
disabled = true

[character]
success_symbol = "[󰥭 ](fg:light_text bg:fourth)"
error_symbol = "[󰥭 ](fg:light_text bg:fourth)"
vimcmd_symbol = "[ ](fg:light_text bg:fourth)"
format = "[ $symbol ](bg:fourth)"
disabled = false

[username]
show_always = true
format = '[ $user ]($style)'
style_user = "fg:dark_text bg:first"
style_root = "fg:dark_text bg:first"
disabled = false

[os]
style = "fg:dark_text bg:first"
disabled = true

[directory]
style = "fg:dark_text bg:second"
read_only_style = "fg:dark_text bg:second"
read_only = "  "
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:light_text bg:third"
format = '[ $symbol $branch ]($style)'

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "fg:subtle_text"
up_to_date = "[ ](fg:success_text)"
untracked = "[ \\($count\\) ](fg:warning_text)"
modified = "[ \\($count\\) ](fg:primary)"
staged = "[ \\($count\\) ](fg:success_text)"
renamed = "[ \\($count\\) ](fg:uncommon_text)"
deleted = "[ \\($count\\) ](fg:error_text)"
conflicted = "[󰕚 \\($count\\) ](fg:danger_text)"
stashed = "[ \\($count\\) ](fg:secondary)"
ahead = "[󰁝 \\($count\\) ](fg:ahead)"
behind = "[󰁅 \\($count\\) ](fg:behind)"
diverged = "[󰁜 \\([$ahead_count](fg:ahead)/[$behind_count](fg:behind)\\)](fg:subtle_text)"

[git_state]
format="[$state\\($progress_current of $progress_total\\)](fg:subtle_text)"

[palettes.powerline_colors]
first = "#eceff4"
second = "#d8dee9"
third = "#4c566a"
fourth = "#434c5e"
background = "#2e3440"
light_text = "#eceff4"
dark_text = "#2e3440"
subtle_text = "#e5e9f0"
success_text = "#a3be8c"
warning_text = "#ebcb8b"
danger_text = "#d08770"
error_text = "#bf616a"
primary = "#88c0d0"
secondary = "#81a1c1"
uncommon_text = "#b48ead"
ahead = "#8fbcbb"
behind = "#b48ead"

